const music = document.querySelector('audio');
const prevButton = document.querySelector('#prev');
const playButton = document.querySelector('#play');
const skipButton = document.querySelector('#skip');
const title = document.querySelector('#title');
const artist = document.querySelector('#artist');

let isPlaying = false;

const songInfo = [
    {
        name: '01-Doom Eternal',//name of the file in the folder
        displayName : 'Doom Eternal', 
        artist: 'Mick Gordon'
    },
    {
        name: '02-Hell on Earth',//name of the file in the folder
        displayName : 'Hell on Earth', 
        artist: 'Mick Gordon'
    },
    {
        name: '03-Deag Nilox - First Priest Death',//name of the file in the folder
        displayName : 'Deag Nilox - First Priest Death', 
        artist: 'Mick Gordon'
    },
    {
        name: '04-Barging In',//name of the file in the folder
        displayName : 'Barging In', 
        artist: 'Mick Gordon'
    },
    {
        name: '05-Demonic Corruption',//name of the file in the folder
        displayName : 'Demonic Corruption', 
        artist: 'Mick Gordon'
    }

]

function ifDisplayNameIsTooLong(songInfo){
    if (songInfo.displayName.length > 25) {
        title.classList.add('long-title');
    }
    else  (title.classList.remove('long-title'))
}

function playSong() {
    isPlaying = true;

    // change the play icon to pause when pressing play
    playButton.classList.replace('bi-play-fill','bi-pause-fill');

    music.play();
}

function pauseSong() {
    isPlaying = false;

    // change the pause icon to play when pressing pause
    playButton.classList.replace('bi-pause-fill','bi-play-fill');

    music.pause();
}

// play or pause event listener (using ternary operator)
playButton.addEventListener('click', () => (isPlaying ? pauseSong() : playSong()));

// load song in into dom
function loadSong(songInfo){
    title.textContent = songInfo.displayName;
    artist.textContent = songInfo.artist;
    music.src = `./music/${songInfo.name}.m4a`;
    ifDisplayNameIsTooLong(songInfo)
}

// current song:
let songIndex = 2;

// next song:
function skipSong(){
     // every click will be added to the songIndex var
     songIndex++;
     // take the songIndex generated by buttons and add it to loadSong func:
    if (songIndex > songInfo.length -1){
        songIndex = 0;
    }
     loadSong(songInfo[songIndex]);
     playSong();
     }

// previous song:
function prevSong(){
    // every click will be deducted from the songIndex var
    songIndex--;
  
    if (songIndex < 0){
        songIndex = songInfo.length -1;
     }
    loadSong(songInfo[songIndex]);
    playSong();
}

// load song into the dom based on songIndex input
// if songIndex = 2 then loadSong func will load the third index in the songInfo array
loadSong(songInfo[songIndex]);

// // add event listener to the buttons
prevButton.addEventListener('click', prevSong);
skipButton.addEventListener('click', skipSong);
